export const NOTES = [
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },

  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
  {
    _id: Math.round(Math.random() * 1e6),
    title: "The title of the note" + Math.round(Math.random() * 1e3),
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quam culpa, at maiores quae deserunt eveniet ullam rerum dignissimos commodi asperiores odio sit quos accusantium ab. Quod, numquam. Error, amet optio.",
    createdAt: new Date(Date.now()),
    updatedAt: new Date(Date.now()),
  },
];
